### PR TITLE
Added TRS-80 Model 1 and Model 3 

### PR DESCRIPTION
**Pull request by jrdcontrolsoft**
Separate files for TRS-80 Model 1 (aclockm1) and Model 3 (aclockm3) added to source, binary, and screenshots.

### CODE REVIEW

**Review by tenox7 — CHANGES_REQUESTED** [review]
Screenshots should go to screenshots/ instead of bootimages/

Thanks!

**Comment by jrdcontrolsoft** [comment]
Sigh. That was dumb of me. Anyway, I put the screenshots in the screenshots
directory of my aclock, jrdcontrolsoft-trs80 branch. But,

1. I was not able to simply "revert" the bootimages directory. I'm using
the plain Github website, not Github desktop. Couldn't find a revert
button. So I manually deleted the 2 wrong files, but that counts as a "new"
change. So that directory has the same files it used to have, but shows an
update even though it's back to the old contents.

2. When I tried to do another pull request, it jumped straight to my
previous one. So I *think* it just counts as an update of the previous pull
request. I really hope that's enough for you to take it from there.

3. Your master aclock has changed in the meantime--it has a new MSXDOS
file. I didn't have to update my master or other branch with that new file
first, did I?

I'm still very awkward with using the github website. (I have used github
in Eclipse, but that only works with Java files. These aren't Java files.)
Thanks for being patient with me. Hope that's good enough for you to work
with!

John Dahlman

**Review by tenox7 — APPROVED** [review]
LGTM

**Comment by tenox7** [comment]
No worries we all started not knowing git. I'm not that proficient in it as well.

**Comment by tenox7** [comment]
And thank you for submitting this and going through the pain. I think it's worth it because you will be credited with it automatically :)

**Pull request merged**
